expname: balanced_real_ships_home
data:
  imsize: 128
  datadir: /home/gitaar9/AI/TNO/detectron/my_marvel_balanced_white
  type: balancedrealships
  radius: 9,12
  near: 7.5
  far: 13.5
  fov: 30
  vmin: 0.0    # 0 deg
  vmax: 0.25     # 60 deg
discriminator:
  hflip: True
training:
  outdir: /home/gitaar9/Desktop/tensorboard_test/graf_balanced_ship_remote
