expname: balanced_real_ships_unresized
data:
  imsize: 128
  datadir: /data/s2576597/graf_datasets/my_marvel_balanced_white_unresized
  type: balancedrealships
  radius: 9,12
  near: 7.5
  far: 13.5
  fov: 30
  vmin: 0.0    # 0 deg
  vmax: 0.25     # 60 deg
discriminator:
  hflip: True
training:
  outdir: /data/s2576597/graf_balanced_real_ships_unresized_results
  batch_size: 16
  lr_g: 0.001
  lr_d: 0.0002
