expname: shapenetships_128_new_plan
data:
  imsize: 128
  datadir: /scratch/s2576597/graf_datasets/ship_renders_train_upper_hemisphere_30_fov #data/carla
  type: shapenetcars
  radius: 10.
  near: 7.5
  far: 12.5
  fov: 30.0
training:
  outdir: /data/s2576597/graf_results/graf_shapenetships_128_mirror
