expname: ships_new_128
data:
  imsize: 128
  datadir: /data/s2576597/graf_datasets/ship_renders
  type: ships
  radius: 10.
  near: 7.5
  far: 12.5
  fov: 30.0
training:
  outdir: /data/s2576597/graf_results
