expname: ships_new_128
data:
  imsize: 128
  datadir: /home/gitaar9/AI/TNO/shapenet_renderer/ship_renders
  type: ships
  radius: 10.
  near: 7.5
  far: 12.5
  fov: 30.0
training:
  outdir: ./output
  batch_size: 2
nerf:
  mirror: True