expname: sncar_128_sym_loss
data:
  imsize: 80
  datadir: /samsung_hdd/Files/AI/TNO/shapenet_renderer/car_renders_train_upper_hemisphere_30_fov
  type: shapenetcars
  radius: 10.
  near: 7.5
  far: 12.5
  fov: 30.0
training:
  outdir: /samsung_hdd/Files/AI/TNO/graf/trained_models
  sym_lambda: 33
  batch_size: 24
nerf:
  mirror: True